Expand error codes in messages
List of error codes defined in https://www.sqlite.org/rescode.html

Test: Cause an exception and verify error codes are expanded:
      SQLiteConstraintException: NOT NULL constraint failed: test.num
      (code 1299 SQLITE_CONSTRAINT_NOTNULL)
Bug: 30014655
Bug: 64262688

Change-Id: Ia4f5fedebea9803805e7ab27fa623a5eec1e5cfe