SyatemUI: Fix pocket lock after 13 QPR1
build error -->

 frameworks/base/packages/SystemUI/src/com/android/keyguard/KeyguardUpdateMonitor.java:2103: error: method updateBiometricListeningState in class KeyguardUpdateMonitor cannot be applied to given types;
                        updateBiometricListeningState(BIOMETRIC_ACTION_UPDATE);
                        ^
  required: int,FaceAuthUiEvent
  found: int
  reason: actual and formal argument lists differ in length

Signed-off-by: aswin7469 <aswinas@pixysos.com>
Signed-off-by: Hưng Phan <phandinhhungvp2001@gmail.com>