Fix a compile error with DEBUG_SERVICE enabled.
Fixes the following compile error that occurs when
DEBUG_SERVICE is set to true.

frameworks/base/services/core/java/com/android/server/am/\
ActiveServices.java:1624: error: variable si might not \
have been initialized
                        + si.intent);

Change-Id: I62851d9d9de18294b555834e042025eeca0ad5ae